export enum NotificationEventType {
  BOOKING_CREATED = 'BOOKING_CREATED',
  BOOKING_ACCEPTED = 'BOOKING_ACCEPTED',
  BOOKING_REJECTED = 'BOOKING_REJECTED',
  QUOTE_CREATED = 'QUOTE_CREATED',
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  TRUCK_POST_PUBLISHED = 'TRUCK_POST_PUBLISHED',
  REWARD_EARNED = 'REWARD_EARNED',
  CHECK_IN_VERIFIED = 'CHECK_IN_VERIFIED',
}
