import { VendorPlan } from '@prisma/client';

export const VENDOR_FOUNDING_OFFER_SETTING_KEY = 'vendor_founding_offer';

export const DEFAULT_VENDOR_FOUNDING_OFFER = {
  enabled: true,
  startAt: '2026-08-05T00:00:00.000Z',
  endAt: '2026-10-04T23:59:59.999Z',
  officialLaunchAt: '2026-10-05T00:00:00.000Z',
  subscriptionDiscountPercent: 50,
  subscriptionDiscountMonths: 9,
  freeTrialMonths: 3,
};

export const VENDOR_PLAN_CONFIG = {
  [VendorPlan.FREE]: {
    plan: VendorPlan.FREE,
    name: 'Free',
    subtitle: 'Basic Discovery',
    monthlyPriceCents: 0,
    foundingMonthlyPriceCentsAfterTrial: 0,
    normalCommissionRate: null,
    foundingCommissionRate: null,
    bookingEnabled: false,
    maxStaffAccounts: 0,
    maxIncludedTrucks: 1,
    additionalTruckMonthlyPriceCents: null,
    analyticsLevel: 'NONE',
    included: [
      'Listed on discovery map',
      'Full profile with photos',
      'Full menu with photos',
      'Customer reviews and ratings',
      'Community tab access',
      'Followers can follow your truck',
      'Follower count visible',
    ],
    notIncluded: [
      'Live drops',
      'QR check-in and rewards',
      'Push notifications to followers',
      'Message followers',
      'Analytics',
      'Event bookings',
      'Staff accounts',
    ],
  },
  [VendorPlan.STARTER]: {
    plan: VendorPlan.STARTER,
    name: 'Starter',
    subtitle: 'Drops & Bookings',
    monthlyPriceCents: 1000,
    foundingMonthlyPriceCentsAfterTrial: 500,
    normalCommissionRate: 0.15,
    foundingCommissionRate: 0.12,
    bookingEnabled: true,
    maxStaffAccounts: 1,
    maxIncludedTrucks: 1,
    additionalTruckMonthlyPriceCents: null,
    analyticsLevel: 'BASIC',
    included: [
      'Everything in Free',
      'Live drops with real-time map',
      'Drop promotions and deals',
      'QR check-in and credit redemption',
      'Push notifications to followers',
      'Message followers broadcast',
      'Event booking requests',
      'Send quotes and accept bookings',
      'Basic analytics',
      '1 staff account',
    ],
    notIncluded: [
      'Featured on discovery section',
      'Search relevance boost',
      'Full earnings analytics',
      'Community booking requests',
      'Multiple truck listings',
      'Advanced analytics',
      'Priority support',
      'Featured badge on profile',
    ],
  },
  [VendorPlan.PRO]: {
    plan: VendorPlan.PRO,
    name: 'Pro',
    subtitle: 'Full Platform',
    monthlyPriceCents: 1900,
    foundingMonthlyPriceCentsAfterTrial: 950,
    normalCommissionRate: 0.12,
    foundingCommissionRate: 0.1,
    bookingEnabled: true,
    maxStaffAccounts: 2,
    maxIncludedTrucks: 1,
    additionalTruckMonthlyPriceCents: null,
    analyticsLevel: 'FULL',
    included: [
      'Everything in Starter',
      'Community booking requests',
      'Featured on discovery section',
      'Search relevance boost',
      'Full earnings and analytics',
      '2 staff accounts',
    ],
    notIncluded: [
      'Multiple truck listings',
      'Advanced analytics',
      'Priority support',
      'Featured badge on profile',
    ],
  },
  [VendorPlan.ELITE]: {
    plan: VendorPlan.ELITE,
    name: 'Elite',
    subtitle: 'Maximum Growth',
    monthlyPriceCents: 4900,
    foundingMonthlyPriceCentsAfterTrial: 2450,
    normalCommissionRate: 0.08,
    foundingCommissionRate: 0.06,
    bookingEnabled: true,
    maxStaffAccounts: 5,
    maxIncludedTrucks: 3,
    additionalTruckMonthlyPriceCents: 1500,
    analyticsLevel: 'ADVANCED',
    included: [
      'Everything in Pro',
      'Up to 3 truck listings included',
      'Up to 5 staff accounts',
      'Advanced analytics and reports',
      'Featured badge on profile',
      'Priority customer support',
      'Early access to new features',
      'Eligible for BiteDrop social media feature',
      'Each truck requires own verification',
    ],
    notIncluded: [],
  },
} as const;

export type VendorFoundingOfferConfig = typeof DEFAULT_VENDOR_FOUNDING_OFFER;
