export enum VendorVerificationDocumentType {
  DSHS_MOBILE_FOOD_VENDOR_LICENSE = 'DSHS_MOBILE_FOOD_VENDOR_LICENSE',
  STATE_OR_LOCAL_FOOD_VENDOR_PERMIT = 'STATE_OR_LOCAL_FOOD_VENDOR_PERMIT',
  FOOD_MANAGER_CERTIFICATION = 'FOOD_MANAGER_CERTIFICATION',
  CERTIFICATE_OF_INSURANCE = 'CERTIFICATE_OF_INSURANCE',
}
